# Google Tag Manager Container Details
gtm_id = "GTM-FTR4X67"      # enter GTM container ID in format "GTM-XXXXXX". This value is invalidated and redundant if the 'override_container_id' parameter below is set to true
gtm_datalayer = "basic"     # set to "basic" to push page metadata into the dataLayer upon page load. Set to other value or blank to disable.

# OPTIONAL - Server-side GTM Settings
gtm_endpoint = ""           # enter hostname of GTM server-side endpoint in format sub.domain.tld. If using standard GTM leave blank: ""

# OPTIONAL - Simo Ahava's GTM Loader server-side client template (https://github.com/gtm-templates-simo-ahava/gtm-loader)
use_custom_library_name = false     # If this is set to true, ensure to set the gtm_library_name variable below and configure the GTM Custom Loader client template inside your ssGTM container
gtm_library_name = "gtm.js"         # if using Simo Ahava's GTM Loader template to enable changing the name of the GTM library, set the document name here (e.g. mylibrary.js) and match it in the client settings online. 
override_container_id = false       # Set this to true if the GTM Loader client is configured to "Override Container ID" where you have added matched your preferred GTM container ID. 

# OPTIONAL - Google Tag Manager Staging Environment
# create an additional "environment" from within the GTM Admin interface meant for "Staging"
# extract the 'gtm_auth' and 'gtm_preview' query parameters from the 'src' URL query in the provided GTM snippet
# this gtm environment snippet activates whenever the HUGO_ENVIRONMENT variable is not set to 'production' (such as running the hugo server)) and the `use_staging_gtm_environment` is set to true.
use_staging_gtm_environment = false
gtm_env_param_gtm_auth = ""     # enter `gtm_auth` string here e.g. "dhxfPfIIp62NuQfRTdCd1w". 
gtm_env_param_gtm_preview = ""  # enter `gtm_preview` string here e.g. "env-8". Leave blank "" 